name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 16 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
  
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    
      - name: General
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: general.svg
          token: ${{ secrets.Metrics_Secret }}
          plugin_languages: yes
          plugin_languages_colors: github
          plugin_languages_limit: 6
          plugin_languages_ignored: html, css, 4D, q
          plugin_languages_details: bytes-size, percentage
          plugin_starlists: yes
          plugin_starlists_languages: yes
          plugin_starlists_limit_languages: 6
          plugin_starlists_languages_ignored: html
          config_order: languages, starlists
          user: coldinke
          template: classic
          base: ""
          config_timezone: Asia/Shanghai

      - name: topics
        uses: lowlighter/metrics@latest
        if: ${{ success() || failure() }}
        with:
          filename: topics.svg
          token: ${{ secrets.Metrics_Secret }}
          plugin_topics: yes
          plugin_topics_limit: 0
          plugin_topics_mode: icons
          plugin_leetcode: yes
          plugin_leetcode_sections: solved, skills, recent
          config_order: topics
          user: coldinke
          template: classic
          base: ""
          config_timezone: Asia/Shanghai
